version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/attache/attache
    steps:
      - checkout
      - run: go get
      - run: go test -v ./...
