// Code generated by go-bindata. DO NOT EDIT.
// sources:
// templates/.at-conf.json.tpl
// templates/index.tpl.tpl
// templates/layout.tpl.tpl
// templates/main.go.tpl

package cmd_new

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _templatesAtConfJsonTpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xaa\xe6\x52\x50\x50\x50\x50\x72\xce\xcf\x2b\x49\xad\x28\x09\xa9\x2c\x48\x55\xb2\x52\x50\xaa\xae\xd6\xf3\x4b\xcc\x4d\xad\xad\x55\xd2\xe1\xaa\x05\x04\x00\x00\xff\xff\x25\xd6\x9d\x61\x23\x00\x00\x00")

func templatesAtConfJsonTplBytes() ([]byte, error) {
	return bindataRead(
		_templatesAtConfJsonTpl,
		"templates/.at-conf.json.tpl",
	)
}

func templatesAtConfJsonTpl() (*asset, error) {
	bytes, err := templatesAtConfJsonTplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/.at-conf.json.tpl", size: 35, mode: os.FileMode(420), modTime: time.Unix(1530466235, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xab, 0x79, 0xc4, 0xe3, 0x38, 0xa2, 0xc8, 0xa2, 0x28, 0x33, 0x17, 0xaf, 0x67, 0x8, 0xa4, 0xc3, 0xd3, 0xcb, 0x42, 0xfa, 0x10, 0xc4, 0x69, 0xe0, 0xdf, 0x88, 0xfb, 0xd4, 0x58, 0x81, 0xe6, 0x6d}}
	return a, nil
}

var _templatesIndexTplTpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x64\xcc\x41\x0a\xc2\x40\x0c\x85\xe1\xbd\xa7\x18\x72\x00\xe7\x02\xd6\x6b\xb8\xef\xcc\x2b\x0d\xc6\x14\x9a\x80\x96\x90\xbb\x0b\x83\xe0\xa2\xdb\xef\x3d\xfe\x88\x8e\x85\x15\x85\x9c\x5d\x40\x99\x0f\x48\xdb\x5e\x88\x80\xf6\xcc\xcb\xff\x60\x7e\x08\x8c\x32\x6f\xc2\xfa\x2c\x3b\x64\xfa\xd9\x0a\x38\x95\x75\xc7\x32\x51\x7d\x63\xae\xcd\xac\xb2\x76\x7c\xae\xcd\x8c\xea\xfd\x1c\x9b\xb7\x7e\xd0\x90\xb1\x7c\x03\x00\x00\xff\xff\xa6\x6a\xf6\x2b\x87\x00\x00\x00")

func templatesIndexTplTplBytes() ([]byte, error) {
	return bindataRead(
		_templatesIndexTplTpl,
		"templates/index.tpl.tpl",
	)
}

func templatesIndexTplTpl() (*asset, error) {
	bytes, err := templatesIndexTplTplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/index.tpl.tpl", size: 135, mode: os.FileMode(420), modTime: time.Unix(1530018161, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xe1, 0x45, 0xc1, 0xcb, 0x9e, 0x77, 0xf6, 0x60, 0x29, 0xc9, 0x27, 0xae, 0x44, 0xbe, 0xcc, 0x7b, 0xe6, 0xb1, 0x89, 0x2c, 0x65, 0xd6, 0xb4, 0x4a, 0xa3, 0x3c, 0x75, 0x69, 0x9c, 0x17, 0x5, 0x8}}
	return a, nil
}

var _templatesLayoutTplTpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xb2\x51\x74\xf1\x77\x0e\x89\x0c\x70\x55\xc8\x28\xc9\xcd\xb1\xe3\xb2\x81\x50\x0a\x0a\x0a\x0a\x36\x19\xa9\x89\x29\x10\x26\x98\x5b\x92\x59\x92\x93\x6a\x57\x5d\x9d\x94\x93\x9f\x9c\xad\xa0\x04\xe6\x2a\x29\xe8\xd5\xd6\x46\x47\xeb\xf9\x25\xe6\xa6\xc6\xc6\x56\x57\xa7\xe6\xa5\xd4\xd6\xda\xe8\x43\x94\xc2\xb5\xc2\xf5\x14\x97\x54\xe6\xa4\x16\x83\x35\x41\xd5\x62\x51\x93\x5c\x94\x59\x50\x82\xa9\xc8\x46\x1f\xe1\x1e\x9b\xa4\xfc\x94\x4a\x2c\xe6\x83\x84\xc1\x1a\x91\xa4\x90\x4d\x80\x68\xb3\xd1\x07\x7b\x12\x10\x00\x00\xff\xff\xd6\xc2\xdf\x26\xfb\x00\x00\x00")

func templatesLayoutTplTplBytes() ([]byte, error) {
	return bindataRead(
		_templatesLayoutTplTpl,
		"templates/layout.tpl.tpl",
	)
}

func templatesLayoutTplTpl() (*asset, error) {
	bytes, err := templatesLayoutTplTplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/layout.tpl.tpl", size: 251, mode: os.FileMode(420), modTime: time.Unix(1529761933, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x66, 0xb7, 0xff, 0xed, 0xfe, 0xac, 0x1e, 0x7f, 0xdc, 0xb9, 0xe0, 0xea, 0x59, 0xaf, 0xd3, 0xf2, 0x4a, 0x4, 0xc2, 0x4f, 0x1f, 0x17, 0xaa, 0xcf, 0x3e, 0x90, 0xd, 0xa, 0x55, 0x13, 0xe0, 0x26}}
	return a, nil
}

var _templatesMainGoTpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x52\x4b\x8f\xd3\x30\x10\xbe\xfb\x57\x0c\x39\x20\x27\xaa\xec\xfb\x4a\x7b\x59\xca\xa2\xbd\xb0\x52\xa9\xe0\x80\x10\xf2\xba\xd3\xd4\xd4\xb1\xdd\xc9\x98\xb6\x44\xf9\xef\x28\x8f\x96\x67\x73\x8a\xfd\x7d\xf3\x3d\x34\x4e\xc6\xee\x4d\x8d\xd0\x18\x17\x84\x70\x4d\x8a\xc4\x20\x05\x00\x40\x11\x90\xf5\x8e\x39\x15\xd3\xd1\xc7\xba\x10\xd3\x6f\xed\x78\x97\x5f\x94\x8d\x8d\x6e\xac\x8d\xde\x7f\x23\x6d\x98\x8d\xdd\x61\x21\x4a\x21\xf8\x9c\x10\xba\x4e\xbd\x37\x0d\xf6\x3d\xb4\x4c\xd9\x32\x74\xe3\xf0\xcc\x53\x0f\xa6\xc5\x37\x31\x30\x9e\x18\xb4\x06\xc2\x43\x76\x84\x9b\x3f\x38\x4b\xdc\x9a\xec\xf9\xd1\x79\xfc\x80\xf4\x1d\xe9\x7f\xe8\x47\x87\xc7\x76\x04\xb4\xfe\x1b\x5b\x3e\xdc\x00\xd6\x71\x8f\x01\x44\x2f\xc4\x36\x07\x0b\xd2\x42\x75\xcd\x5b\xc2\x53\x70\x2c\x8f\x30\x94\x57\x2b\x6c\x53\x0c\x2d\x7e\x22\xc7\x48\x0b\x20\xa8\xe6\xfb\x43\xc6\x96\xcb\xb9\x96\xae\x60\xfd\xbc\x7c\xbe\x03\x17\x1c\x3b\xe3\xdd\x0f\x04\x3b\xd7\xab\xf4\x2d\xa3\x77\x6f\xd7\x5f\x9f\xc2\x06\x4f\xf2\x1f\x59\xf9\xf9\xcb\xcb\x99\x71\x01\x48\x14\xe9\x62\x43\xc8\x99\x02\x58\x35\xb6\x96\xa5\x5a\x61\xd8\x20\xc9\xc2\x0d\x2a\xc5\x02\x82\xf3\xe5\xd5\x6d\xd8\xaa\xbc\x8c\x9a\x94\x46\x31\xb8\xbb\xff\xb5\x84\x18\xb9\x65\x32\x49\xbe\xbe\xa6\xea\xfa\x72\xe4\xbb\xed\xc8\x7e\x75\x3f\x68\xce\x1a\xc3\xe7\x63\xad\x1e\x0d\x1b\xef\x83\x44\xa2\x89\xdc\x4f\x2f\xe3\x77\xcc\xa4\xa4\x56\x39\xc8\x72\xc8\xf3\x33\x00\x00\xff\xff\xbe\x23\xb7\xd6\x68\x02\x00\x00")

func templatesMainGoTplBytes() ([]byte, error) {
	return bindataRead(
		_templatesMainGoTpl,
		"templates/main.go.tpl",
	)
}

func templatesMainGoTpl() (*asset, error) {
	bytes, err := templatesMainGoTplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/main.go.tpl", size: 616, mode: os.FileMode(420), modTime: time.Unix(1530466349, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xf4, 0x97, 0x34, 0x3e, 0xac, 0x35, 0x2e, 0x64, 0x51, 0x2a, 0x3, 0x63, 0xe, 0xf4, 0xab, 0xa1, 0x89, 0x50, 0xfc, 0x58, 0xdc, 0x9b, 0xf5, 0x9f, 0xb9, 0xc7, 0x80, 0xf4, 0x99, 0xcf, 0x3a, 0x2d}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"templates/.at-conf.json.tpl": templatesAtConfJsonTpl,

	"templates/index.tpl.tpl": templatesIndexTplTpl,

	"templates/layout.tpl.tpl": templatesLayoutTplTpl,

	"templates/main.go.tpl": templatesMainGoTpl,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"templates": &bintree{nil, map[string]*bintree{
		".at-conf.json.tpl": &bintree{templatesAtConfJsonTpl, map[string]*bintree{}},
		"index.tpl.tpl":     &bintree{templatesIndexTplTpl, map[string]*bintree{}},
		"layout.tpl.tpl":    &bintree{templatesLayoutTplTpl, map[string]*bintree{}},
		"main.go.tpl":       &bintree{templatesMainGoTpl, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
