name: Build & Test

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.5
      - run: go get -v ./...
      - run: go test -v ./...

